spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
---
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest
    username: hhjang
    password: hhjang1
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
---
my-app:
  admin-username: admin@gmail.com
  admin-password: admin
  general-username: user@gmail.com
  general-user-password: user
  client-id: clientIdTestValue
  client-secret: clientSecretTestValue